version: '3.7'

services:

  # Admin app
  canary-dashboard:
    build:
      context: ../blue-canary-dashboard
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_TIMEZONE: ${APP_TIMEZONE}
    image: brightfish/blue-canary-dashboard
    volumes:
      - ../blue-canary-dashboard:/var/www/app:rw

  # Push api
  canary-aggregator:
    build:
      context: ../blue-canary-aggregator
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_TIMEZONE: ${APP_TIMEZONE}
    image: brightfish/blue-canary-aggregator
    volumes:
      - ../blue-canary-aggregator:/var/www/app:rw
      - ../blue-canary-dashboard/config/canary:/var/www/app/config/canary:rw

  # NGINX
  canary-server:
    build:
      context: ../blue-canary-server
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_TIMEZONE: ${APP_TIMEZONE}
    image: brightfish/blue-canary-server
    volumes:
      - ../blue-canary-dashboard/public:/var/www/app/public:ro
    labels:
      traefik.frontend.headers.SSLRedirect: 'false'
      traefik.frontend.headers.isDevelopment: 'true'
