#!/usr/bin/env bash

# Load helpers functions and variables
. "$(pwd)/shell-helper"

# Run all tests (unit + integration)
${DOCKER} exec \
  -e APP_ENV=testing \
  -e DB_HOST=host.docker.internal \
  -e DB_DATABASE=blue_canary_tests \
  canary-dashboard \
  ./vendor/bin/phpunit
